### ISSUE TITLE
Doesn´t inline "...!important" styles

### ISSUE THREAD

**Issue by dimoooooooon** [jonkemp/gulp-inline-css#17]
width: 100% !important;
converts to
width: 100%

**Comment by jonkemp** [comment]
This is a known issue. Juice has the same functionality. It does inline the important style and throws the non-important one out.

**Comment by koomai** [comment]
Note: The styles have to match exactly for this to happen. For example:

`margin: 0 !important;` doesn't override `margin-bottom: 10px`.

**Comment by AndrewEastwood** [comment]
+1. I added ```display:none !important;``` but it printed just ```display:none;```

**Comment by AndrewEastwood** [comment]
is there any chance to get it there?

**Comment by jonkemp** [comment]
This is not something that's planned. I don't even understand what the benefit is here.

**Comment by AndrewEastwood** [comment]
this is for when you creates email templates then some email-clients ignore display:none but not display:none !important

**Comment by jonkemp** [comment]
This will work in the next update.
