### ISSUE TITLE
How can I remove html class attribute ?

### ISSUE THREAD

**Issue by liyaodong** [jonkemp/gulp-inline-css#27]
### Source
```html
<div class="header"></div>
```

```css
.header { color: #fff };
```
### inline process
```html
<div class="header" style="color: #fff;"></div>
```

why not clean all class attribute ? if mail page load the html, god know the class `.header` has some style  rule ...

**Comment by jonkemp** [comment]
An option to do this was just added in the inline css module. So you should just be able to set the option in gulp and it will get passed through.

https://github.com/jonkemp/inline-css/pull/2

**Comment by darklow** [comment]
Thanks, good feature. Yet it is merged, but not documented yet

**Comment by jonkemp** [comment]
Pull requests accepted. :smiley:
