### ISSUE TITLE
Next release?

### ISSUE THREAD

**Issue by danmindru** [jonkemp/gulp-inline-css#29]
Hi there & happy new year!
 
I saw there are quite a few new commits in [https://github.com/jonkemp/inline-css](inline-css), are you planning to make a release and bump both repos sometime soon?

Thanks a lot for you efforts :)

**Comment by jonkemp** [comment]
Yes, likely. No new features are planned though.

**Comment by danmindru** [comment]
Thanks, looking forward :-)
Have a nice day!
