### ISSUE TITLE
!important being removed 

### ISSUE THREAD

**Issue by christopherwise** [jonkemp/gulp-inline-css#33]
Anytime I have an !important tag inline it is removed. Any way to preserve the tag?

Use case is to hide an input element, gmail needs an !important tag on display:none;.

**Comment by jonkemp** [comment]
It should be preserved. This plugin uses the inline-css module. Take a look at the test suite.

https://github.com/jonkemp/inline-css/blob/master/test/main.js#L90

The tests pass so I'm not sure what to tell you. If you can replicate the problem, my advice is to fork the repo and add failing tests.

**Comment by christopherwise** [comment]
Will do, thanks!
