### ISSUE TITLE
Using the same property multiple times

### ISSUE THREAD

**Issue by koen-dev** [jonkemp/gulp-inline-css#55]
I would like to inline the same property multiple times for a e-mail template. Is this possible and if so how?

Example:
```sass
.w100p {
    display:inline-block;
    vertical-align:top;
    text-align:left;
    width:100%;
    min-width:285px;
    max-width:100%;
    width:-webkit-calc(230400px - 48000%);
    min-width:-webkit-calc(100%);
    width:calc(230400px - 48000%);
    min-width:calc(100%);
}
```

Should result in:
```html
<td style="display: inline-block; vertical-align:top; text-align:left; width:100%; width:calc(230400px - 48000%); min-width:285px; min-width:-webkit-calc(100%); min-width:calc(100%); max-width:100%;"></td>
```

**Comment by jonkemp** [comment]
It should inline the class everywhere it finds it.

**Comment by tobyelliott** [comment]
@jonkemp It should but it doesn't. It takes the first value it finds.

**Comment by jonkemp** [comment]
Maybe it is a bug caused by the use of calc. Just guessing here.

**Comment by tobyelliott** [comment]
I tested it using font-size.

**Comment by tobyelliott** [comment]
@jonkemp Right, so if you have a link and a style tag both with the same styles, the external stylesheet takes precedence regardless of the ordering of the markup.
